// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK8OJI-uVp5HEu-9jRyl1_Ki1eLps5DUg',
    appId: '1:1035158830052:web:d94e8386c2c3658c0d65f1',
    messagingSenderId: '1035158830052',
    projectId: 'elder-care-medical',
    authDomain: 'elder-care-medical.firebaseapp.com',
    storageBucket: 'elder-care-medical.firebasestorage.app',
    measurementId: 'G-DPVYDYXNGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nlEDZyd98akCh7ZZT_dvlrtTyTEzmqY',
    appId: '1:1035158830052:android:0967df63f386699a0d65f1',
    messagingSenderId: '1035158830052',
    projectId: 'elder-care-medical',
    storageBucket: 'elder-care-medical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAokLp-QOhe6DbhhwNoVh23WPtcQYvhYfI',
    appId: '1:1035158830052:ios:4a632a79f9cbb8c50d65f1',
    messagingSenderId: '1035158830052',
    projectId: 'elder-care-medical',
    storageBucket: 'elder-care-medical.firebasestorage.app',
    iosClientId: '1035158830052-qklni46fs1peu0k2n32had3n320ntvmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
